In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
df=pd.read_csv('game_knn.csv')

In [ ]:
df

Name  Age Gender     Sport
0    A   32      M  Football
1    B   40      M   Neither
2    C   16      F   Cricket
3    D   34      F   Cricket
4    E   55      M   Neither
5    F   40      M   Cricket
6    G   20      F   Neither
7    H   15      M   Cricket
8    I   55      F  Football
9    J   15      M  Football

In [ ]:
df.drop(columns='Name', inplace=True)

In [ ]:
df = pd.get_dummies(df, drop_first=True)

In [ ]:
df

Age  Gender_M  Sport_Football  Sport_Neither
0   32         1               1              0
1   40         1               0              1
2   16         0               0              0
3   34         0               0              0
4   55         1               0              1
5   40         1               0              0
6   20         0               0              1
7   15         1               0              0
8   55         0               1              0
9   15         1               1              0

In [ ]:
y=df.iloc[:,2].values.reshape(-1,1)

In [ ]:
df.drop(columns='Sport', inplace=True)

In [ ]:
df=pd.get_dummies(df, drop_first=True)

In [ ]:
df

Age  Gender_M
0   32         1
1   40         1
2   16         0
3   34         0
4   55         1
5   40         1
6   20         0
7   15         1
8   55         0
9   15         1

In [ ]:
x=df.iloc[:,0:2].values

In [ ]:
y

array([['Football'],
       ['Neither'],
       ['Cricket'],
       ['Cricket'],
       ['Neither'],
       ['Cricket'],
       ['Neither'],
       ['Cricket'],
       ['Football'],
       ['Football']], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder()

In [ ]:
y = le.fit_transform(y)

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:251: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
y

array([1, 2, 0, 0, 2, 0, 2, 0, 1, 1])

In [ ]:
x

array([[32,  1],
       [40,  1],
       [16,  0],
       [34,  0],
       [55,  1],
       [40,  1],
       [20,  0],
       [15,  1],
       [55,  0],
       [15,  1]])

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)


In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
classifier = KNeighborsClassifier(n_neighbors = 3, metric = 'euclidean')

In [ ]:
classifier.fit(x,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [ ]:
pred_y = classifier.predict(x)

In [ ]:
pred_y

array([0, 0, 0, 0, 2, 0, 0, 1, 0, 1])

In [ ]:
y

array([1, 2, 0, 0, 2, 0, 2, 0, 1, 1])

In [ ]:
classifier.predict(sc.fit_transform([[33,0]]))

array([0])