In [ ]:
import pandas as pd


In [ ]:
df = pd.read_csv('tissue.csv')

In [ ]:
df

x1  x2     y
0   7   7   bad
1   7   4   bad
2   3   4  good
3   1   4  good

Divide input and output

In [ ]:
x = df.iloc[:, 0:2].values

In [ ]:
y = df.iloc[:, 2].values.reshape(-1,1)

In [ ]:
y

array([['bad'],
       ['bad'],
       ['good'],
       ['good']], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder()

In [ ]:
y = le.fit_transform(y)
y

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:251: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0, 0, 1, 1])

In [ ]:
y

array([0, 0, 1, 1])

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
classifier = KNeighborsClassifier(n_neighbors=3, metric='euclidean')

In [ ]:
classifier.fit(x,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [ ]:
pred_y = classifier.predict(x)

In [ ]:
pred_y

array([0, 0, 1, 1])

In [ ]:
y

array([0, 0, 1, 1])

In [ ]:
classifier.predict([[3,7]])

array([1])

In [ ]:
classifier.predict([[4,7]])

array([0])