In [ ]:
import pandas as pd


In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Verzeo ML Feb Batch/Loan_logistic.csv")
df

gender married   ch  income  loanamt status
0      Male      No  1.0    5849      NaN      Y
1      Male     Yes  1.0    4583    128.0      N
2      Male     Yes  1.0    3000     66.0      Y
3      Male     Yes  1.0    2583    120.0      Y
4      Male      No  1.0    6000    141.0      Y
..      ...     ...  ...     ...      ...    ...
609  Female      No  1.0    2900     71.0      Y
610    Male     Yes  1.0    4106     40.0      Y
611    Male     Yes  1.0    8072    253.0      Y
612    Male     Yes  1.0    7583    187.0      Y
613  Female      No  0.0    4583    133.0      N

[614 rows x 6 columns]

In [ ]:
df.isnull().sum()

gender     13
married     3
ch         50
income      0
loanamt    22
status      0
dtype: int64

In [ ]:
df.dropna(inplace=True)

In [ ]:
df

gender married   ch  income  loanamt status
1      Male     Yes  1.0    4583    128.0      N
2      Male     Yes  1.0    3000     66.0      Y
3      Male     Yes  1.0    2583    120.0      Y
4      Male      No  1.0    6000    141.0      Y
5      Male     Yes  1.0    5417    267.0      Y
..      ...     ...  ...     ...      ...    ...
609  Female      No  1.0    2900     71.0      Y
610    Male     Yes  1.0    4106     40.0      Y
611    Male     Yes  1.0    8072    253.0      Y
612    Male     Yes  1.0    7583    187.0      Y
613  Female      No  0.0    4583    133.0      N

[529 rows x 6 columns]

In [ ]:
df.isnull().sum()

gender     0
married    0
ch         0
income     0
loanamt    0
status     0
dtype: int64

In [ ]:
df.drop(columns='gender', inplace=True)

In [ ]:
df

married   ch  income  loanamt status
1       Yes  1.0    4583    128.0      N
2       Yes  1.0    3000     66.0      Y
3       Yes  1.0    2583    120.0      Y
4        No  1.0    6000    141.0      Y
5       Yes  1.0    5417    267.0      Y
..      ...  ...     ...      ...    ...
609      No  1.0    2900     71.0      Y
610     Yes  1.0    4106     40.0      Y
611     Yes  1.0    8072    253.0      Y
612     Yes  1.0    7583    187.0      Y
613      No  0.0    4583    133.0      N

[529 rows x 5 columns]

In [ ]:
df.dtypes

married     object
ch         float64
income       int64
loanamt    float64
status      object
dtype: object

In [ ]:
df = pd.get_dummies(df, drop_first=True)

In [ ]:
df

ch  income  loanamt  married_Yes  status_Y
1    1.0    4583    128.0            1         0
2    1.0    3000     66.0            1         1
3    1.0    2583    120.0            1         1
4    1.0    6000    141.0            0         1
5    1.0    5417    267.0            1         1
..   ...     ...      ...          ...       ...
609  1.0    2900     71.0            0         1
610  1.0    4106     40.0            1         1
611  1.0    8072    253.0            1         1
612  1.0    7583    187.0            1         1
613  0.0    4583    133.0            0         0

[529 rows x 5 columns]

In [ ]:
import numpy as np


In [ ]:
y = df['status_Y'].values

In [ ]:
x = df.drop(columns='status_Y').values

In [ ]:
x

array([[1.000e+00, 4.583e+03, 1.280e+02, 1.000e+00],
       [1.000e+00, 3.000e+03, 6.600e+01, 1.000e+00],
       [1.000e+00, 2.583e+03, 1.200e+02, 1.000e+00],
       ...,
       [1.000e+00, 8.072e+03, 2.530e+02, 1.000e+00],
       [1.000e+00, 7.583e+03, 1.870e+02, 1.000e+00],
       [0.000e+00, 4.583e+03, 1.330e+02, 0.000e+00]])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 0)

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
lr = LogisticRegression()

In [ ]:
lr.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
y_pred = lr.predict(x_test)

In [ ]:
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0], dtype=uint8)

In [ ]:
y_test

array([0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0], dtype=uint8)

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
cm = confusion_matrix(y_test, y_pred)

In [ ]:
cm

array([[16, 17],
       [ 3, 70]])

In [ ]:
score = lr.score(x_test, y_test)

In [ ]:
score

0.8113207547169812

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc = StandardScaler()

In [ ]:
x = sc.fit_transform(x)

In [ ]:
x

array([[ 0.42830502, -0.1280731 , -0.19425027,  0.74864676],
       [ 0.42830502, -0.3920766 , -0.97101451,  0.74864676],
       [ 0.42830502, -0.46162142, -0.29447791,  0.74864676],
       ...,
       [ 0.42830502,  0.45380195,  1.37180667,  0.74864676],
       [ 0.42830502,  0.37224939,  0.54492861,  0.74864676],
       [-2.33478468, -0.1280731 , -0.13160799, -1.33574344]])

In [ ]:
df

ch  income  loanamt  married_Yes  status_Y
1    1.0    4583    128.0            1         0
2    1.0    3000     66.0            1         1
3    1.0    2583    120.0            1         1
4    1.0    6000    141.0            0         1
5    1.0    5417    267.0            1         1
..   ...     ...      ...          ...       ...
609  1.0    2900     71.0            0         1
610  1.0    4106     40.0            1         1
611  1.0    8072    253.0            1         1
612  1.0    7583    187.0            1         1
613  0.0    4583    133.0            0         0

[529 rows x 5 columns]

In [ ]:
lr.predict(sc.transform([[1.0,500,200,0]]))

array([1], dtype=uint8)